### ISSUE TITLE
How can I send-commands and receive values

### ISSUE THREAD

**Issue by OllisGit** [csowada/ebus#4]
Moin,
first: thx, for this library...but I have two Question: 

I use the following code (from tag: ebus-dist1.0.0) and the ebus sends a lot of data, but how can I send a command to recieve e.g. the "solar-temp" or "Aussentemperatur"?

```
IEBusConnection connection = new EBusSerialNRJavaSerialConnection(portName);
EmulatorCapture captureWriter = new EmulatorCapture(captureFile);
// Beide zusammenbringen
connection = new EBusCaptureProxyConnection(connection, captureWriter);
		
EBusController controller = new EBusController(connection);
EBusHighLevelService service = new EBusHighLevelService(controller);
EBusConfigurationJsonReader jsonCfgReader = new EBusConfigurationJsonReader(service.getConfigurationProvider());

File filex = new File("src/main/resources/common-configuration.json");
jsonCfgReader.loadConfigurationFile(filex.toURL());		

controller.start();
...
```

Which version of the ebus-lib should I use? The "dist-1.0.0" or the "master"? 
Id had some problems to compile the master-source, so I switched to dist. But if you say, it is better to use the "master", I will try to compile again.

BR
Olli

**Comment by csowada** [comment]
You should use the master branch, the release is too old. Only the core lib ``de.csdev.ebus`` in the master branche is okay, the rest is outdated and I should remove it in the next release. Also the readme.md is  not up to date. You should look at my unit tests as an example. But keep in mind that this is an alpha release and the api is not stable. 

https://github.com/csowada/ebus/tree/master/de.csdev.ebus/src/test/java/de/csdev/ebus

**Comment by OllisGit** [comment]
Thx for your fast response!
I checked out the master branch, but now I have more questions ;-)

- Why do yu remove the play-methode (public void play(final File inputFile, final double replaySpeed)) from the Emulator-Class?
- I have a lot of captured ebus-files and now I want to replay such files. How can I do this? Should I copy the old play-Method to the new class or should I use the emulator.writeBytes(b) methode?

hmmm... the dist EBusEmulatorConnection use a lot of other stuff. Sending othe telegrams like 1,2,3, why?

```
        emu.write(new byte[] { 1, 2, 3, 45, (byte) 0xAA });
        emu.play(file);
        emu.write(new byte[] { 1, 2, 3, 45, (byte) 0xAA });
        emu.play(file);
        emu.write(new byte[] { 2, 1, 1, 1, (byte) 200, 100, 45, (byte) 0xAA });
        emu.play(file);

```
BR
Olli
